
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int tmul = 6;
  public static final int trest = 3;
  public static final int tnum = 2;
  public static final int tsum = 4;
  public static final int ttan = 13;
  public static final int pare2 = 10;
  public static final int tpot = 7;
  public static final int pare1 = 9;
  public static final int tmod = 8;
  public static final int EOF = 0;
  public static final int tcos = 12;
  public static final int error = 1;
  public static final int tsen = 11;
  public static final int tdiv = 5;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "tnum",
  "trest",
  "tsum",
  "tdiv",
  "tmul",
  "tpot",
  "tmod",
  "pare1",
  "pare2",
  "tsen",
  "tcos",
  "ttan"
  };
}

